---
language: python
python: "2.7"
sudo: required
dist: trusty
env:
  global:
  - secure: "EUn+IhQs6+LKglrGlDyJxQa/gau4WTJrZ13T8WRV55vF6qUwqRek6HE5reO0cp4sEHJ83wO1k6fc207SEGHSoO0toeYwsyYCVAZGij7LYsAKtXjxz8tv3UMT5YC/FmnKc8Ym/0AZMgQU7CEMBVfz8EaQVq4Hfw770K+wbI77tATO0tnhYtZiTBycogXWAjEvRLV9ZWkmuVjwIQ0Dh8Vp5SKUSthBXosURqVKv71Tb+sxLwsWfaawS0jC0NUXq3OE4bichVzC38975V6Y6YXYBYcckypCD/g/FMK9NvbaeQciFRmNtOp50h3+LaPFrBIeTNHT4Sa7Xh6IOK1yVm7mIZRxE37J5WsPsHRTeOyzfsglaCxyGzsqM/eZR7Xau172L77c9nDi70KI1NlgKCmqxUcdYjCv3ZoGTbkNUCpeuaSkxFmkEUEXbXEBQmVSCAx7c8wQ7eI/GkNvSp/dVosfawHedbPv1c0lAfjuJVY8ExPrVxq9ZNyRKue/1clmXNtuJof30aIK7KUE4Fcz28Vp7frB/l7aywtR0IvmQsH6JR9F8nDL6Xv833CjbBUes3zAwxuH1mdxSvxIkhvRPKbZcHC6SiXQg110vihqYjdFcESMBEmgzZGofzJf8bLTfeWpPe2JXQKphxD2BMI8sBYlyhGguukSQLjhfsoyZQA1Z94="
  - secure: "QS1VNWyb+TYX2/mgg8aMEgD9ywGYnn11DI6nJS/djKijvIRkWPrD+7/ej5S7yGgGht2cUS4l33kUtkYvK+yAor4zfDuLicCnroj3YZ1OWYqpa0dSCmlcvu0VPm/ROrCA4eLKQ0lQIgpCy6ct/sk69ehCszBwsxF+cVx8ZZzVhtPhiOV7/BWIGsP7vZfdRNGhwmkRBlauOPyN4WxsPYWUHGUMiWlqkU/O3D4YaTtBlCe6JadAaQYhqrygveCgqeQqT9xm/zpPaqwKhvmgXjjteg3+81uuT05AsUB58aXKy3ciAtZTEKNnONtwHFBXBIaLLADoVBapilaCkUInAV2L59y3iFeWbkXjOxSgc5M52/gS7JjLDeXvUVmIahrP0jlYBk8qLTVdsMOcxjWjbE/0kpCuCmrbo4xXDLpXORq2HZk0SBXV0wh6cZNkXtc5SeESo30Yd5qrVfFfpWEITI8hhxvngCuobERflrNvj+auZGjj+UkXPcWEhxPbVnvn7bwDzZL5C0FNRXw67XvwYp40uztDfzpip6fVsV27Curfvs0Xims4UcR2K1Fdx/WdQUnhsH2cEDR3MV9fIVhib74WCNZrtCx0ozTJ3Gimq6baUO4AMUPxyhyy82AAnp1gRN56fbB1B+RrHQxWmTkLtZadXRQFWD8ITMCP2bchX8zPgzw="
git:
  submodules: false
before_install:
 - git submodule update --init --recursive
 - git submodule foreach git pull origin master
 - sudo apt-get update -qq
 - sudo apt-get install -qq squashfs-tools uuid python-apt python-pycurl btrfs-tools
install:
 - sudo pip install ansible
 - sudo pip install docker-py
script:
- cd squashible
- sudo ansible-playbook -i hosts_generator.py squashible.yml -e "live_os=centos_7"
- ls -lah live_output
- sudo chown -R travis:travis live_output
- cd live_output
after_success:
    "curl --ftp-create-dirs -T '{vmlinuz,initrd.img,rootfs.img}' -u $FTP_USER:$FTP_PASSWORD ftp://images.squashible.com/images/squashible-centos-7-minimal/"
