---
language: python
python: "2.7"
sudo: required
dist: trusty
env:
  global:
  - secure: "Sumk52OFdgskIlZWiiof7GFv182yn9RX87Cw5mDaB7re26/mim6+kYU7A0xd/Etj/zbYH56LP5b46DjJMx28mHoenPEnhxV4Fk8NNb2XLqoUGTXFwtKbi2d8MlXkxVLnPT7aNvhTmmih3d1k2xCZ4CbQHdWyZYru/RsxiNT1ywhpPSgcq+SS7pg+bvV0K9R+HDqJhjT02SEhiEOiDoIHA2n5xWTTDJ8MRl7p6Wq1z8OvOroCzVC6UDXKBPalvDfN9NP1qBCRhTI6bPg5t7V4+DOUNBVKujWv0Z/xXpteZlwXckK5kxIUgireOGuD/ZF5eksRgRhW3VfIO0m933vrx4cFPy004NhJCnyzIjNzCey2SOpXLH9bYs3hZTK8DeQ7in+zxN3NenKM3KwktQsLUz1TzolhBmB3Qgl1dXirbkCZmY3U8/POokzhHr+fEwcO3wBnMV0rPemK2/WPSguWG3fyvWsxYi+5M3wvjtPxYwcaxM51ZHONTNWlV4Q/N7/TZbno8aUMLFSi44vinJdchnN3kJeOcZgPEzvKMWcwvPZ1icypzgXaGHxRZaLQIWE5oZszBD2noqm99V7xeJEOO25P1xx4+MEmXbr0Sb36Sgvk+dYuMbeME7GvJa+epgrYQrAg/Svqf9jM6ofuhWgKsPT+fgegOvbtHNq+4hW4B2Q="
  - secure: "PCaJlExDtAN9zsp6nCPIKvP42P18Ya6bOlNGCG4Zm1Rx4v47/Qx4FserpxhGVLJ3aTkJJVsUBZLTzaAmVT/Rylzi2KD4D+zzIga7DXX4MjeEOrLnp4frxcgHMHME+C1edrw6Sv4bHAdRL4WOpMgw2svZOAOAc+wia5exbWIZ2Yi3bS9V2z1BqZDwBt0qqT4AOZlMp8O/PLbZokH5n2ETt6iCPPl+eSHWGLFxwGvUKbSsCURUfcZ9MZr9ALHKDw35x6ESiBnBuOrfp82xBbZmisThoyXstg8y9ezuGxvh4cLNtgfJbk0m8a9PIk43V8y5ca8vZFQ1Ac0XbZRE8vDDi7sUIJ5URjLYVeyKMKndFKurCSDspH4orapKRWwj0itPzZALNyetGkGpYEqB1syB9pAanfFgBTNjInuKk42GIuhAoic4KKsfNVywmfVZQU29tbtVXWDmB+Rq9s6OQz3wH9zPfrV+Z6YbBQSW+QR/VQKmSsZbcjq+bkv5XSVIiW0FRJbEKLiRtbk8K9CliLUnh44OZXCUVdmBO0vzTFCnJkxvly5gvxw6lXMWkZwJuPErpK0ttkSNkVawZpzLA3Ipb/tbwgPza+oaNf+ma6IiK/3eKLfXS1a6ZZYihg+u2vPEpWbZKIF5hEblA7bxeD/81Q+s9hb38JZQnJdhzVaa4PE="
git:
  submodules: false
before_install:
 - git submodule update --init --recursive
 - git submodule foreach git pull origin master
 - sudo apt-get update -qq
 - sudo apt-get install -qq squashfs-tools uuid python-apt python-pycurl btrfs-tools
install:
 - sudo pip install ansible
 - sudo pip install docker-py
script:
- cd squashible
- sudo ansible-playbook -i hosts_generator.py squashible.yml -e "live_os=centos_7"
- ls -lah live_output
- sudo chown -R travis:travis live_output
- cd live_output
after_success:
    "curl --ftp-create-dirs -T '{vmlinuz,initrd.img,rootfs.img}' -u $FTP_USER:$FTP_PASSWORD ftp://images.squashible.com/images/squashible-centos-7-minimal/"
